# NumPy Basics

In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10) # it is as like as range 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2) # this is step size 

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,10) # 10 evenly space points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
# [] - 1d then [[]] - 2d

In [20]:
# range and linspace both are different

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(5,5)

array([[0.73288468, 0.78913141, 0.36453263, 0.14972963, 0.28660128],
       [0.73522101, 0.4595478 , 0.59368194, 0.14069214, 0.02396605],
       [0.19548884, 0.78667828, 0.80393778, 0.17637372, 0.57692207],
       [0.93586217, 0.43577024, 0.14012982, 0.13437156, 0.84377073],
       [0.74170866, 0.17049897, 0.01457844, 0.40380507, 0.66290998]])

In [10]:
np.random.randn(2)

array([-1.91824003, -1.26707181])

In [11]:
np.random.randn(2,2)

array([[-1.06679084,  0.44306151],
       [-2.57148106,  0.14178565]])

In [16]:
np.random.randint(1,50,10)

array([48, 43, 37, 22, 14, 24, 22, 18, 48, 33])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([24, 35, 12, 19, 38, 27, 31, 42,  7, 10])

In [23]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 25 into shape (3,3)

In [27]:
arr.reshape(5,5) # 5*5 = 25 so this is basic rule of checking

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

42

In [31]:
ranarr.min()

7

In [32]:
ranarr

array([24, 35, 12, 19, 38, 27, 31, 42,  7, 10])

In [33]:
ranarr.argmax()

7

In [34]:
ranarr.argmin()

8

In [35]:
arr.shape

(25,)

In [40]:
arr = arr.reshape(5,5)

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int64')

In [43]:
from numpy.random import randint

In [44]:
randint(2,3)

2

# NumPy Indexing and Selection

In [45]:
import numpy as np

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[8]

8

In [49]:
arr[1:5]

array([1, 2, 3, 4])

In [50]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[:5]

array([0, 1, 2, 3, 4])

In [53]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

__Numpy Array is different then normal python array__

In [54]:
arr[0:5] = 100

In [55]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr = arr[0:6]

In [59]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [60]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_of_arr[:] = 99

In [62]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy = arr.copy()

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy[:] = 100

In [68]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

__By using copy we have saved our original array__

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

__Indexing two d array - matrics__

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

__Since it is with two bracket we need to pass two value__

In [73]:
arr_2d[0][0]

5

In [74]:
arr_2d[0]

array([ 5, 10, 15])

In [75]:
arr_2d[1][1]

25

In [76]:
arr_2d[2][1]

40

__Lets do comma single bracket notification and it is receommended to use single bracket notification less error__

In [77]:
arr_2d[2,1]

40

In [79]:
arr_2d[1,2]

30

In [80]:
arr_2d[1][2]

30

__Example for sub array__

In [81]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [82]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [83]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [88]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

__Conditional Selection__

In [89]:
arr = np.arange(1,11)

In [90]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
bool_arr = arr > 5

In [93]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

__Now we can do conditional selection__

In [94]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

__Lets do it in one step__

In [95]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [96]:
arr[arr < 3]

array([1, 2])

In [97]:
arr_2d = np.arange(50).reshape(5,10)

In [98]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [101]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations

- Array with Array
- Array with Scalars
- Universal Array Functions

In [102]:
import numpy as np

In [103]:
arr = np.arange(0,11)

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

__Array with Array__

In [105]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [106]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [107]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

__Array with Scalar Operations__

In [108]:
arr  + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [109]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [110]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [111]:
1/0

ZeroDivisionError: division by zero

In [112]:
arr / arr

<ipython-input-112-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [113]:
1 / arr

<ipython-input-113-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [114]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

__Universal Array Functions (ufunc)__

In [115]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [116]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [118]:
np.max(arr)

10

In [119]:
arr.max()

10

In [120]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [121]:
np.log(arr)

<ipython-input-121-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])